version: '3'

services:
  nginx:
    image: nginx
    container_name: "laravel-nginx"
    ports:
      - "8080:80"
    volumes:
      - ./:/src
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
  php:
    build:
      ./infra/php
    container_name: "laravel-php"
    volumes:
      - ./:/src
  mysql:
    image: mysql
    container_name: "laravel-mysql"
    environment:
     - MYSQL_ROOT_PASSWORD=root
     - MYSQL_DATABASE=holy_place_photo
     - MYSQL_USER=laravel
     - MYSQL_PASSWORD=laravel
    ports:
      - 13306:3306
    volumes:
      - ./data/mysql:/var/lib/mysql
  redis:
    image: redis
    container_name: "laravel-redis"
    ports:
        - "16379:6379"